### ISSUE TITLE
Smatch score on Bio on AMRBART

### ISSUE THREAD

**Issue by zekunzhao** [goodbai-nlp/AMR-DomainAdaptation#1]
Hello, author

Thanks for opening this repo for your exciting work. When I made inferences on the Bio domain data, I could not get the smatch score reported in your paper for the Bio domain with the AMRBART model. Which model is you using for this cross-domain project? 

Thanks,
zekun

**Comment by goodbai-nlp** [comment]
Hi, @zekunzhao 

We used "xfbai/AMRBART-large-finetuned-AMR2.0-AMRParsing" for cross-domain evaluation, the parsed results are avaliable [here](https://1drv.ms/t/s!ArC7JSpdBblgtDQl1AtJoObLAvtR?e=WaHIME).
